from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent

## Raw Data (tracked in the repo / DVC, read-only inputs)
DATA_DIR = PROJECT_ROOT / "data"
RAW_DATA_DIR = DATA_DIR / "raw"

## Dataset Paths
TRAIN_DATA_PATH = RAW_DATA_DIR / "train_FD004.txt"
TEST_DATA_PATH = RAW_DATA_DIR / "test_FD004.txt"
RUL_DATA_PATH = RAW_DATA_DIR / "RUL_FD004.txt"


## Artifacts (everything generated by the pipeline lives under here,
## organized by kind, so nothing writes back into data/ or the repo root)
ARTIFACTS_DIR = PROJECT_ROOT / "artifacts"

PROCESSED_DATA_DIR = ARTIFACTS_DIR / "data" / "processed"
MODELS_DIR = ARTIFACTS_DIR / "models"
EXPERIMENTS_DIR = ARTIFACTS_DIR / "experiments"
PLOTS_DIR = ARTIFACTS_DIR / "plots"

REPORTS_DIR = PROJECT_ROOT / "reports"



# Randomness
RANDOM_STATE = 42

# Data
ENGINE_COLUMN = "unit_number"
TARGET_COLUMN = "RUL"

# Feature Engineering
ROLLING_WINDOW = 5
LAGS = [1, 2, 3]

# Splitting
VALIDATION_SIZE = 0.2

# Scaling
SCALER = "standard"

# Target Engineering
DEFAULT_RUL_CAP = 125